# version: "3.9" Daft 

# services:
#   backend:
#     build: ./backend
#     ports:
#       - "8080:8080"
#     command: npm run start
#     depends_on:
#       - redis

#   frontend:
#     build: ./frontend
#     ports:
#       - "4200:80"
#     environment:
#       - API_URL=http://backend:8080

#   redis:
#     image: redis
#     ports:
#     - 6379:6379
#     build:
#       context: .